# Generated by Django 4.2 on 2023-06-08 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_shippingfee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingFee',
        ),
    ]
