# Generated by Django 4.2 on 2023-05-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_foodimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
