# Generated by Django 4.2 on 2023-05-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_fooditem_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='ingredients',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
