# Generated by Django 4.2 on 2023-05-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_fooditem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodimage',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_images', to='menu.fooditem'),
        ),
    ]
