# Generated by Django 4.2 on 2023-05-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_foodimage_food_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categorydefault',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
