# Generated by Django 4.2 on 2023-07-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_fooditem_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='ingredients',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
