# Generated by Django 4.2 on 2023-06-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax_data',
        ),
    ]
